version: '3.8'

services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_backend
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: gostarter
      DB_PORT: 5432
      JWT_SECRET: pN9vZb3A8sEtmZ5q0Jx+gY6u2r7nDbFjH3p0X5fMvWspN9vZb3A8sEtmZ5q0Jx+gY6u2r7nDbFjH3p0X5fMvWs
    ports:
      - "8080:8080"
    # volumes:
    #   - .:/app
    command: ["./main"]

volumes:
  db_data: 